# Generated by Django 3.2.4 on 2021-06-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguareteapp', '0003_auto_20210630_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productremera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
