# Generated by Django 3.2.4 on 2021-07-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaguareteapp', '0006_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='usado',
            new_name='digital',
        ),
    ]
