# Generated by Django 3.2.4 on 2021-07-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaguareteapp', '0008_auto_20210705_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
