# Generated by Django 3.2.4 on 2021-07-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaguareteapp', '0013_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
